#!/bin/bash

WALLET="0x0525177c8afe8680d7ad1da30ca183e482cfcd6404c1e09d83fd3fa2994fd4b8"

BASE_CMD="torii -w $WALLET --http.cors_origins '*'"


if [ "$1" = "persistent" ]; then
    # remove tmp folder to avoid `waitForEntityChange: Timeout of 6000ms` error
    rm -rf ./tmp

    if [ -n "$2" ]; then
        torii --db-dir ./tmp/indexer.db -w $WALLET --http.cors_origins '*' --events.historical "$2"
    else
        torii --db-dir ./tmp/indexer.db -w $WALLET --http.cors_origins '*'
    fi
else
    $BASE_CMD
fi